volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}



services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
      build: true
    volumes:
      - production_django_media:/app/api/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
      build: true
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
      build: truek
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'

  redis:
    build: true


  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
      build: true
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
