# Generated by Django 5.1.9 on 2025-06-05 15:15

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('image', models.ImageField(upload_to='portfolio/images/', verbose_name='Bild')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('description', tinymce.models.HTMLField(verbose_name='Beschreibung')),
                ('image', models.ImageField(upload_to='portfolio/images/', verbose_name='Bild')),
                ('image2', models.ImageField(blank=True, upload_to='portfolio/images/', verbose_name='optionales Bild')),
                ('gh', models.URLField(blank=True, verbose_name='Github Repo')),
                ('live', models.URLField(blank=True, verbose_name='Live Demo')),
                ('tags', models.ManyToManyField(to='portfolio.skills', verbose_name='Tags')),
            ],
        ),
    ]
