# Generated by Django 5.1.9 on 2025-06-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='tags',
            field=models.ManyToManyField(blank=True, to='portfolio.skills', verbose_name='Tags'),
        ),
    ]
