# Generated by Django 5.1.9 on 2025-08-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_projects_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='in_progress',
            field=models.BooleanField(default=False, verbose_name='In Arbeit'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.ImageField(blank=True, upload_to='portfolio/images/', verbose_name='Bild'),
        ),
    ]
