# Generated by Django 5.1.9 on 2025-08-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projects_in_progress_alter_skills_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.FileField(blank=True, upload_to='portfolio/images/', verbose_name='Bild'),
        ),
    ]
